package org.musetest.extensions;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.junit.Assert.*;

public class PlaceholderTest
    {
    @Test
    public void testSomething()
        {
        assertTrue("just need a test", true);
        }
    }
